### ISSUE TITLE
Kastari menu is showing lunch of two days

### ISSUE THREAD

**Issue by Immuuni** [jtiala/ruoka#3]
Firts of all thank you for this site! 

At the moment, On Kastari menu, there is lunches 1-4 and again 1-3. I think it is fetching also next week's friday lunch.

**Comment by jtiala** [comment]
You're welcome!
Yeah, that seems to be true. They include menu for two weeks in the same json if it's ready, I guess. Earlier this week the json had only menus for current week. I'll fix this issue this weekend. Thanks for reporting!

**Comment by Immuuni** [comment]
This seems to fixed!

**Comment by jtiala** [comment]
Actually, it's not. They just haven't published next weeks menus yet, so they are not showing. I didn't have the time to fix this last weekend, but I'll try to find time soon!
